backend:
  name: git-gateway
  repo: Omdaprog/netlify_cms_monorepo

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog1'
    label: 'blog1'
    folder: 'blog/content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Image", name: "thumbnail", widget: "image"}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog2'
    label: 'blog2'
    folder: 'blog2/content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: "Image", name: "thumbnail", widget: "image"}
      - { label: 'Body', name: 'body', widget: 'markdown' }


      
